apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:      
      color: blue
      version: v1
  template:
    metadata:
      name: shopping-site-pod
      labels:
        version: v1
        color: blue
    spec:
      containers:
        - name: shopping-app-container
          image: ramarao388/shoppingsite
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
