---
apiVersion: v1
kind: Service
metadata:
  name: shopping-site-testing-svc  
spec:
  type: LoadBalancer
  selector:    
    color: green
  ports:
    - port: 80
      targetPort: 8080
     
